# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cinchize"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Bergoo"]
  s.date = "2012-03-27"
  s.description = "Create dynamic Cinch IRC-bots and daemonize them, without the need of writing any code"
  s.email = "victor.bergoo@gmail.com"
  s.executables = ["cinchize"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/cinchize",
    "cinchize.gemspec",
    "examples/cinchize.init",
    "lib/cinchize.rb"
  ]
  s.homepage = "http://github.com/netfeed/cinchize"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Create dynamic Cinch IRC-bots and daemonize them"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<cinch>, [">= 2.0.1"])
      s.add_runtime_dependency(%q<daemons>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<cinch>, [">= 2.0.1"])
      s.add_dependency(%q<daemons>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<cinch>, [">= 2.0.1"])
    s.add_dependency(%q<daemons>, [">= 0"])
  end
end

